[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://vistaverde.hu https://*.vistaverde.hu" 
    X-Frame-Options = "ALLOW-FROM https://vistaverde.hu"









